name: Run RSpec Tests
on: [push, pull_request]

env:
  RUBY_VERSION: 2.3.5
  MYSQL_DATABASE_HOST: localhost
  MYSQL_USER: root
  MYSQL_ROOT_PASSWORD: r00tp@ss
  MYSQL_DATABASE: mysms_test
  RAILS_ENV: test

jobs:
  rspec-test:
    name: RSpec
    runs-on: ubuntu-16.04
    env:
      DB_HOST: ${{ env.MYSQL_DATABASE_HOST }}
      DB_USER: ${{ env.MYSQL_USER }}
      DB_PASSWORD: ${{ env.MYSQL_ROOT_PASSWORD }}      

    services:
        mysql:
          image: mysql:5.7
          ports:
            - 3306

    steps:
      - uses: actions/checkout@v2
      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}    
      - name: Install dependencies
        run: |
          gem install bundler -v 1.17
          bundle install
      - name: Initialize database
        run: |
          bundle exec rake db:create
          bundle exec rake db:migrate
      - name: Run tests
        run: bundle exec rspec        
